import Head from 'next/head';
import Image from 'next/image';
import NextLink from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';
import cn from 'classnames';
import MobileMenu from '../components/MobileMenu';

function NavItem({ href, text }) {
  const router = useRouter();
  const isActive = router.asPath === href;

  return (
    <NextLink href={href}>
      <a
        className={cn(
          isActive
            ? 'font-semibold text-gray-800'
            : 'font-normal text-gray-600',
          'hidden lg:inline-block sm:px-12 sm:py-2 rounded-lg hover:bg-orange-200 transition-all'
        )}
      >
        <span className="capsize">{text}</span>
      </a>
    </NextLink>
  );
}

const Home = ({ title, children, isHome }) => {
  const [isShown, setIsShown] = useState(false);
  let timer = 0;
  const mouseEnter = () => {
    timer = setTimeout(() => {
      setIsShown(true);
    }, 100);
  };

  const mouseLeave = () => {
    /* setTimeout(() => {
      setIsShown(false);
      clearTimeout(timer);
    }, 200); */
    setIsShown(false);
    clearTimeout(timer);
  };

  return (
    <div className="max-w-7xl mx-auto bg-beige">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center px-8">
        <div className="lg:mx-auto">
          <nav
            className={`flex items-center w-full relative justify-between mx-auto pt-8 ${
              !isHome && 'sm:pb-16'
            }  border-gray-200 text-gray-900`}
          >
            <div className="ml-[-0.60rem] text-lg">
              <MobileMenu />
              <NavItem href="/" text="Home" />
              <NavItem href="/about" text="About" />
              <div
                onMouseEnter={mouseEnter}
                onMouseLeave={mouseLeave}
                className="inline-block group"
              >
                <div className="hidden font-normal text-gray-600 lg:inline-block sm:px-12 sm:py-2 rounded-lg hover:bg-orange-200 transition-all">
                  Portfolio
                </div>
                {isShown && (
                  <ul className="absolute animate-fade m-0 z-10 bg-beige  rounded-lg">
                    <div className="p-1 mt-2">
                      <NextLink href="/portfolio/engineering">
                        <a className="block whitespace-no-wrap hover:bg-orange-200 ">
                          <li className="px-2 py-1">Engineering</li>
                        </a>
                      </NextLink>
                      <NextLink href="/portfolio/motion-graphics">
                        <a className="block whitespace-no-wrap hover:bg-orange-200 ">
                          <li className="px-2 py-1">Motion Graphics</li>
                        </a>
                      </NextLink>
                      <NextLink href="/portfolio/3d">
                        <a className="block whitespace-no-wrap hover:bg-orange-200 ">
                          <li className="px-2 py-1">3D</li>
                        </a>
                      </NextLink>
                      <NextLink href="/portfolio/sketch">
                        <a className="block whitespace-no-wrap hover:bg-orange-200 ">
                          <li className="px-2 py-1">Sketchbook</li>
                        </a>
                      </NextLink>
                      <NextLink href="/portfolio/art">
                        <a className="block whitespace-no-wrap hover:bg-orange-200 ">
                          <li className="px-2 py-1">Art Paintings</li>
                        </a>
                      </NextLink>
                    </div>
                  </ul>
                )}
              </div>
              <NavItem href="/photography" text="Photography" />
              <NavItem href="/films" text="Film Readings" />
            </div>
          </nav>
        </div>
        <main className="my-0 ">{children}</main>
      </div>
    </div>
  );
};

export default Home;
